version: "3.9"
services:
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./data:/data
    command: "osrm-routed --max-matching-size 10000 --max-table-size 10000 --max-viaroute-size 10000 --algorithm ch /data/map.osrm"
